title: "Öğr. Gör. Gani Mustafa İnegöl"
email: gani.inegol@kocaeli.edu.tr
description: "Denizcilikte Stratejik Karar Verme ve İleri Metodolojik Çözümler"
baseurl: "" 
url: "https://drgmi95.github.io" 

featured_book:
  title: "Görünmeyen Engeller: Gemideki Kültür Çatışmaları"
  image: "https://img.kitapyurdu.com/v1/getImage/fn:11910620/wh:true/wi:500"
  akakce: "https://www.akakce.com/arastirma-inceleme-kitaplari/en-ucuz-gorunmeyen-engeller-gemideki-kultur-catismalari-fiyati,964860670.html"
  amazon: "https://www.amazon.com.tr/dp/B0DHWYV4XN"
  kitapyurdu: "https://www.kitapyurdu.com/kitap/gorunmeyen-engeller-gemideki-kultur-catismalari/706449.html"
