title: "Öğr. Gör. Gani Mustafa İnegöl"
email: gani.inegol@kocaeli.edu.tr
description: "Denizcilikte Stratejik Karar Verme ve İleri Metodolojik Çözümler"
url: "https://drgmi95.github.io"
baseurl: ""

# Kitap Bilgileri ve Satış Linkleri
featured_book:
  title: "Görünmeyen Engeller: Gemideki Kültür Çatışmaları"
  image: "https://img.kitapyurdu.com/v1/getImage/fn:11910620/wh:true/wi:500"
  akakce: "https://www.akakce.com/arastirma-inceleme-kitaplari/en-ucuz-gorunmeyen-engeller-gemideki-kultur-catismalari-fiyati,964860670.html"
  kitapyurdu: "https://www.kitapyurdu.com/kitap/gorunmeyen-engeller-gemideki-kultur-catismalari/706449.html"
  amazon: "https://www.amazon.com.tr/dp/6253881523?tag=akakcetr-21&linkCode=ogi&th=1&psc=1&psc=1"
  idefix: "https://www.idefix.com/gorunmeyen-engeller-gemideki-kultur-catismalari-p-6306076?vendorId=10235&ref=akakce&v=1.67.5"
  dr: "https://www.dr.com.tr/kitap/gorunmeyen-engeller-gemideki-kultur-catismalari/arastirma-tarih/sosyoloji/urunno=0002157639001?utm_source=akakce&utm_medium=cpc&v=1.85.4"
